import { Separator } from 'renderer/components/ui/separator'
import { TooltipProvider } from 'renderer/components/ui/tooltip'
import * as Editor from 'renderer/components/editor'
import { useEditor } from 'renderer/hooks/editor'
import Head from './head'

const content = `
  <h1>Closing toilet-seat lids may not stop spread of germs</h1>
  <media></media>
  <blockquote>Many people believe that putting the toilet-seat lid down helps to prevent the spread of dangerous germs and viruses. A recent study pretty much dispels this supposition. A team of microbiologists from the University of Arizona conducted research on the aerial activity of viral particles after a toilet is flushed. The scientists determined that there is little difference in the spread of germs, regardless of whether the lid is up or down. Microbiologist Dr Charles Gerba has been studying lavatory pathogens for nearly five decades. He said: "All that air when you flush goes somewhere, and it carries the viruses that are in the toilet bowl out of it." He said a flush forces bacteria out from under the lid and contaminates nearby areas.</blockquote>
  <ul>
    <li>Many people believe that putting the toilet-seat lid down helps to prevent</li>
    <li>Many people believe that putting the toilet-seat lid down helps to prevent</li>
    <li>Many people believe that putting the toilet-seat lid down helps to prevent</li>
    <li>Many people believe that putting the toilet-seat lid down helps to prevent</li>
    <li>Many people believe that putting the toilet-seat lid down helps to prevent</li>
  </ul>
  <p>The researchers tested the spread of a test virus in two bathrooms after a flush. The virus was one not able to infect humans. They flushed one bowl with the lid up, and another with the lid down. After a minute, they used a sponge to swab the surfaces in the toilet. They concluded that there were no significant statistical differences in the quantities of the virus in the two bathrooms. They added that the results "demonstrate that closing the toilet lid prior to flushing does not mitigate the risk of contaminating bathroom surfaces, and that disinfection of all restroom surfaces may be necessary after flushing or after toilet-brush use" to cut the spread of germs. They also said it was important to disinfect the water in the bowl.</p>
  <p>Many people believe that putting the toilet-seat lid down helps to prevent the spread of dangerous germs and viruses. A recent study pretty much dispels this supposition. A team of microbiologists from the University of Arizona conducted research on the aerial activity of viral particles after a toilet is flushed. The scientists determined that there is little difference in the spread of germs, regardless of whether the lid is up or down. Microbiologist Dr Charles Gerba has been studying lavatory pathogens for nearly five decades. He said: "All that air when you flush goes somewhere, and it carries the viruses that are in the toilet bowl out of it." He said a flush forces bacteria out from under the lid and contaminates nearby areas.</p>
  <ol>
    <li>Many people believe that putting the toilet-seat lid down helps to prevent</li>
    <li>Many people believe that putting the toilet-seat lid down helps to prevent</li>
    <li>Many people believe that putting the toilet-seat lid down helps to prevent</li>
    <li>Many people believe that putting the toilet-seat lid down helps to prevent</li>
    <li>Many people believe that putting the toilet-seat lid down helps to prevent</li>
  </ol>
  <p>The researchers tested the spread of a test virus in two bathrooms after a flush. The virus was one not able to infect humans. They flushed one bowl with the lid up, and another with the lid down. After a minute, they used a sponge to swab the surfaces in the toilet. They concluded that there were no significant statistical differences in the quantities of the virus in the two bathrooms. They added that the results "demonstrate that closing the toilet lid prior to flushing does not mitigate the risk of contaminating bathroom surfaces, and that disinfection of all restroom surfaces may be necessary after flushing or after toilet-brush use" to cut the spread of germs. They also said it was important to disinfect the water in the bowl.</p>
  <p>Many people believe that putting the toilet-seat lid down helps to prevent the spread of dangerous germs and viruses. A recent study pretty much dispels this supposition. A team of microbiologists from the University of Arizona conducted research on the aerial activity of viral particles after a toilet is flushed. The scientists determined that there is little difference in the spread of germs, regardless of whether the lid is up or down. Microbiologist Dr Charles Gerba has been studying lavatory pathogens for nearly five decades. He said: "All that air when you flush goes somewhere, and it carries the viruses that are in the toilet bowl out of it." He said a flush forces bacteria out from under the lid and contaminates nearby areas.</p>
  <p>The researchers tested the spread of a test virus in two bathrooms after a flush. The virus was one not able to infect humans. They flushed one bowl with the lid up, and another with the lid down. After a minute, they used a sponge to swab the surfaces in the toilet. They concluded that there were no significant statistical differences in the quantities of the virus in the two bathrooms. They added that the results "demonstrate that closing the toilet lid prior to flushing does not mitigate the risk of contaminating bathroom surfaces, and that disinfection of all restroom surfaces may be necessary after flushing or after toilet-brush use" to cut the spread of germs. They also said it was important to disinfect the water in the bowl.</p>
  <p>Many people believe that putting the toilet-seat lid down helps to prevent the spread of dangerous germs and viruses. A recent study pretty much dispels this supposition. A team of microbiologists from the University of Arizona conducted research on the aerial activity of viral particles after a toilet is flushed. The scientists determined that there is little difference in the spread of germs, regardless of whether the lid is up or down. Microbiologist Dr Charles Gerba has been studying lavatory pathogens for nearly five decades. He said: "All that air when you flush goes somewhere, and it carries the viruses that are in the toilet bowl out of it." He said a flush forces bacteria out from under the lid and contaminates nearby areas.</p>
  <p>The researchers tested the spread of a test virus in two bathrooms after a flush. The virus was one not able to infect humans. They flushed one bowl with the lid up, and another with the lid down. After a minute, they used a sponge to swab the surfaces in the toilet. They concluded that there were no significant statistical differences in the quantities of the virus in the two bathrooms. They added that the results "demonstrate that closing the toilet lid prior to flushing does not mitigate the risk of contaminating bathroom surfaces, and that disinfection of all restroom surfaces may be necessary after flushing or after toilet-brush use" to cut the spread of germs. They also said it was important to disinfect the water in the bowl.</p>
  <p>Many people believe that putting the toilet-seat lid down helps to prevent the spread of dangerous germs and viruses. A recent study pretty much dispels this supposition. A team of microbiologists from the University of Arizona conducted research on the aerial activity of viral particles after a toilet is flushed. The scientists determined that there is little difference in the spread of germs, regardless of whether the lid is up or down. Microbiologist Dr Charles Gerba has been studying lavatory pathogens for nearly five decades. He said: "All that air when you flush goes somewhere, and it carries the viruses that are in the toilet bowl out of it." He said a flush forces bacteria out from under the lid and contaminates nearby areas.</p>
  <p>The researchers tested the spread of a test virus in two bathrooms after a flush. The virus was one not able to infect humans. They flushed one bowl with the lid up, and another with the lid down. After a minute, they used a sponge to swab the surfaces in the toilet. They concluded that there were no significant statistical differences in the quantities of the virus in the two bathrooms. They added that the results "demonstrate that closing the toilet lid prior to flushing does not mitigate the risk of contaminating bathroom surfaces, and that disinfection of all restroom surfaces may be necessary after flushing or after toilet-brush use" to cut the spread of germs. They also said it was important to disinfect the water in the bowl.</p>
  <p>Many people believe that putting the toilet-seat lid down helps to prevent the spread of dangerous germs and viruses. A recent study pretty much dispels this supposition. A team of microbiologists from the University of Arizona conducted research on the aerial activity of viral particles after a toilet is flushed. The scientists determined that there is little difference in the spread of germs, regardless of whether the lid is up or down. Microbiologist Dr Charles Gerba has been studying lavatory pathogens for nearly five decades. He said: "All that air when you flush goes somewhere, and it carries the viruses that are in the toilet bowl out of it." He said a flush forces bacteria out from under the lid and contaminates nearby areas.</p>
  <p>The researchers tested the spread of a test virus in two bathrooms after a flush. The virus was one not able to infect humans. They flushed one bowl with the lid up, and another with the lid down. After a minute, they used a sponge to swab the surfaces in the toilet. They concluded that there were no significant statistical differences in the quantities of the virus in the two bathrooms. They added that the results "demonstrate that closing the toilet lid prior to flushing does not mitigate the risk of contaminating bathroom surfaces, and that disinfection of all restroom surfaces may be necessary after flushing or after toilet-brush use" to cut the spread of germs. They also said it was important to disinfect the water in the bowl.</p>
  <p>Many people believe that putting the toilet-seat lid down helps to prevent the spread of dangerous germs and viruses. A recent study pretty much dispels this supposition. A team of microbiologists from the University of Arizona conducted research on the aerial activity of viral particles after a toilet is flushed. The scientists determined that there is little difference in the spread of germs, regardless of whether the lid is up or down. Microbiologist Dr Charles Gerba has been studying lavatory pathogens for nearly five decades. He said: "All that air when you flush goes somewhere, and it carries the viruses that are in the toilet bowl out of it." He said a flush forces bacteria out from under the lid and contaminates nearby areas.</p>
  <p>The researchers tested the spread of a test virus in two bathrooms after a flush. The virus was one not able to infect humans. They flushed one bowl with the lid up, and another with the lid down. After a minute, they used a sponge to swab the surfaces in the toilet. They concluded that there were no significant statistical differences in the quantities of the virus in the two bathrooms. They added that the results "demonstrate that closing the toilet lid prior to flushing does not mitigate the risk of contaminating bathroom surfaces, and that disinfection of all restroom surfaces may be necessary after flushing or after toilet-brush use" to cut the spread of germs. They also said it was important to disinfect the water in the bowl.</p>
`

function Create() {
  const editor = useEditor({ content })

  if (!editor) return null
  return (
    <TooltipProvider delayDuration={0}>
      <div className="flex h-full flex-col">
        <Head editor={editor} />
        <Separator />
        <div className="flex-1 overflow-auto">
          <div className="p-11">
            <Editor.Content editor={editor} />
          </div>
        </div>
      </div>
    </TooltipProvider>
  )
}

export default Create
